"""content plan and finance

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 11:50:17.642660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('rubric', sa.String(length=30), nullable=False),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('publish_time', sa.String(length=5), nullable=False),
    sa.Column('hook', sa.String(length=300), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_items_day'), ['day'], unique=False)

    op.create_table('fin_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('monthly_limit', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('content_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('file', sa.String(length=100), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_refs_item_id'), ['item_id'], unique=False)

    op.create_table('fin_recurring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('next_due', sa.Date(), nullable=False),
    sa.Column('remind_days', sa.Integer(), nullable=False),
    sa.Column('reminded_for', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['fin_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fin_recurring', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fin_recurring_next_due'), ['next_due'], unique=False)

    op.create_table('fin_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['fin_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fin_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fin_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_transactions_day'), ['day'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_transactions_day'))
        batch_op.drop_index(batch_op.f('ix_fin_transactions_category_id'))

    op.drop_table('fin_transactions')
    with op.batch_alter_table('fin_recurring', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_recurring_next_due'))

    op.drop_table('fin_recurring')
    with op.batch_alter_table('content_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_refs_item_id'))

    op.drop_table('content_refs')
    op.drop_table('fin_categories')
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_day'))

    op.drop_table('content_items')
    # ### end Alembic commands ###
